### ISSUE TITLE
Forager sharing

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#198]
- [x] Add a header panel which shows information for the current directory including name and number of files.  If 1k+ files, say "1k+".  Eventually we will add pagination, but not now
- [x] Add a button saying "Share" to the header
- [x] When clicked, open a modal
- [x] Modal asks for username and message
- [x] Prepopulate message with "I am inviting you to share files with me via portal.dataskeptic.com"
- [x] When user competes the share, email the recipient
- [ ] if the recipient doesn't have an account, create one in users.ds.com.  When creating their account, instead of copying `sys/msgs/welcome.md`, copy `sys/msgs/welcome-shared.md`
- [x] Add a Forager App to the recipient's Dashboard which is shared to this sub-directory as root.
- [ ] Whenever the original user is viewing the folder *or any nested folders*, display an avatar circle of the users with access to the shared folder

**Comment by Heartless49** [comment]
The last two points that are on here will need to be discussed; coping the file in s3 is currently not possible due to a permissions issue on s3 that i explained before, and the icons for users that have access would require a different type of table/data model than we're currently setup for.

The table/data model is possible, but would take a bit longer for the actual setup. Maybe hold off on this feature until after launch?
