### ISSUE TITLE
Capture address during checkout

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#270]
Store needs to capture address and any product details to uniquely identify what was ordered including size.

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164506337246064">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164506337246066">image.png</a>

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

We are capturing the address; this bug was resolved the day that it happened. All data related to a sale is stored in the JSON file that is saved upon order success.

Attached is a screenshot of my successful order data which includes my address - blanked out for privacy reasons.

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

Below, in the same file, is a list of each of the products purchased and their related data.
