### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#306]
- [x] When a request hits express, follow all the existing routes.  If no route match, before 404 page, instead, check for a landing page
- [x] Check in DynamoDB to see if an object called `LANDING_PAGE:/promo3` exists, if `/promo3` or `/promo3` was the `path` of the request
- [x] Expect a record like this:
```
{
  "title": "Portal Promo3 option",
  "body": "Thanks for checking out promo3!",
  "stripe_subscription_id": "dfafadddf",
  "button_name": "Sign up",
  "initial_apps": [
    {"app": "forager", "path": "users/{{newuser}}/"},
    {"app": "forager", "path": "users/promo3/shared_to_promo_people/"}
  ]
}
```
- [ ] Store which landing page was used to create the account
- [ ] Write a file to the main bucket in `/sys/users/{{newuser}}/details.json`

**Comment by Heartless49** [comment]
Building this out, the object that needs to be in DynamoDB for this to work properly is

```
{
  "body": "This is a testing landing page.",
  "button_name": "Sign Up",
  "initial_apps": {
    "home": {
      "alias": "forager",
      "base": "users/{{email}}/",
      "clone": false,
      "delete": false,
      "description": "Your personal storage in Portal.",
      "name": "My Files",
      "read": true,
      "write": false
    },
    "test": {
      "alias": "forager",
      "base": "users/test/shared_to_promo_people/",
      "clone": false,
      "delete": false,
      "description": "Test user shared files.",
      "name": "Test Files",
      "read": true,
      "write": false
    }
  },
  "object_id": "LANDING_PAGE:/test",
  "owner": "cory@dataskeptic.com",
  "stripe_subscription_id": "dfafadddf",
  "title": "Test Landing Page"
}
```
Forager works with a very specific set of data, and this is the format for a user to have apps "installed" on their dashboard. Here are the reasons/explainations:
1. `initial_apps` must be an `Object`, with the first-level keys being the `slug` for the app instance. This is how the user can go to `/app/home` and arrive at their application. This can literally be anything, even just a `uuid` if we wanted. Having multiple users with `home` will not cross data as it is user/instance specific and not shared.
2. `alias` is the slug for the "Core App" that is being instanced. This is required so that we know it's a `forager` instance.
3. `name` and `description` are the display settings for the app on their Dashboard. `icon` CAN also be added, however it is optional. If any of these 3 keys are `undefined` then the instance will inherit the value of the "Core App", in this case, Forager.
4. `read`, `write`, `clone`, and `delete` are necessary and VERY important. If these are `undefined` then they all default to `false`.
- `read`: The ability to "use" the app. An app can be installed, but have it's `read` set to `false` and the app would no longer be "visible" to the user at all - it would seem as if it was deleted.
- `write`: The ability to change the settings of an installed app after install. This should be false, unless you want them to be able to change the root directory, or name/description, etc... of an installed app.
- `clone`: This is literally only for "Core Apps", so this should always be `false`. It CAN be true, but this basically allows the user to make instances of the app... so literally "copy" and app and slightly modify the settings.
- `delete`: If this is enabled, then the user can delete the app from their dashboard any time they want via the delete button. With it set to `false`, the app cannot be removed by the user and is therefore a permanently installed app.
5. `base` is the "root" directory for the Forager instance, and is a Forager-specific setting - all apps have settings that are like this and specific to that application only - it is called "base" and not "root" because JS freaks out about that being a reserved word.

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

Regarding "Store which landing page was used to create the account", and "Write a file to the main bucket in /sys/users/{{newuser}}/details.json":

- Are we storing this value IN `details.json`?
- If so, do we want that to be placed there, since it will be editable by that user?
- In the case that we do not want the user to be able to edit it, we can always make this `.details.json` instead, as the user will not be able to see the file.
- If we're not storing this detail in `details.json`, where are we storing it?

**Comment by kylepolich** [comment]
> Are we storing this value IN details.json?

Yes

> If so, do we want that to be placed there, since it will be editable by that user?

It's in `/sys/user/` not in `/user/`, so they shouldn't see it.  No editing by the user.
