### ISSUE TITLE
Cannot login after updates

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#388]
[cannot-login.mp4.zip](https://github.com/data-skeptic/fast-spa/files/4364083/cannot-login.mp4.zip)

**Comment by kylepolich** [comment]
@Heartless49 I think this has something to do with the Stripe integration.  When I set up an landing page with ` ` as the stripe ID, it works.  The Stripe Id I put in _IS_ definitely correct.  But even if it were not, we would still want a better error out experience than what we have now, so we need a fix either way.

**Comment by Heartless49** [comment]
I am unable to reproduce this problem, but i agree that the error should be displayed in a better way. The only problem is that if this is directly related to the stripe id that is being used, then there is nothing we can really show the user that would make any sense.

The error itself is specifically the subscription ID being invalid. Nothing about the login, or registration process, is failing other than stripe rejecting a session request.

I'm going to add a toast that will alert the user, if this happens, stating "Invalid signup offer." while logging the message "Error validating Stripe Subscription ID." and the actual error in the console for our debugging.

The problem that i foresee happening here if this gets reached though is that the user will have no way/option to continue. The only solution would be to redirect them to another landing page that is guaranteed to work, however they would lose the plan that they were originally trying to signup with.

A further discussion about how to handle this case should be brought up later - maybe we can come up with a good "catch" for these situations.

**Comment by Heartless49** [comment]
Ooh, we should have an landing page specifically for user's that reached an error - if they get the first error, it can generate our own portal token and redirect them to that page for sign-up.

This page could then ONLY accept registrations from user's with a valid token so that when they register we would know what landing page failed, when, and who reached the error. 

This would give user's a seamless registration process and still slow is to look into any errors.

Just a thought.
