### ISSUE TITLE
API integration stopped working

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#396]
The `key` value is not getting populated.  Empty string is sent.

![image](https://user-images.githubusercontent.com/1054674/77256582-6bbb0180-6c2c-11ea-8754-62bfad640c0d.png)

TOP PRIORITY:

# Get production working again!

But while you are there, consider how much of #397 is low hanging fruit.

**Comment by Heartless49** [comment]
This is resolved in https://github.com/data-skeptic/fast-spa/pull/399

It is not that the API stopped working, it wasn't populating the keys because you are in the root of your instance of forager, therefore it has no path.

This is resolved by simply ensuring that it shows the entire key for the items - the other issue is that now it is `dest_key` instead of the original `dest_prefix`. This has now been added to the list of keys to populate, and will not be an issue anymore.
