### ISSUE TITLE
Wierd!

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#581]
Cory, after reviewing this video, move this ticket to the **Backlog**.  Just wanted to be sure you saw it but this is very low priority.

http://recordit.co/ZJtCr5VoOZ

**Comment by Heartless49** [comment]
Nothing weird about it; the HTML that is being saved is using relative urls for all of their resources, and since we don't have those resources on our server, it can't find them.

In order for this to work and actually display everything, when the html is saved/generated, it would need to find all `src`, and `href` attributes that start with `/` and prepend them with `${domain}/`.
